server:
    port: 8080

spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        username: "root"
        password: "021112"
        url: jdbc:mysql://localhost:3306/daily_anime